// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommissionMe.Migrations
{
    [DbContext(typeof(CommissionMeDbContext))]
    [Migration("20240723190743_InitialSeedData")]
    partial class InitialSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommissionMe.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PostImg")
                        .HasColumnType("text");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PostImg = "https://media.wired.com/photos/5a13e367eceb990b7e519957/master/w_2560%2Cc_limit/Alice-X-Zhang.jpg",
                            Private = false,
                            ProfileId = 2,
                            StyleId = 2,
                            Title = "Best Friends"
                        },
                        new
                        {
                            Id = 2,
                            PostImg = "https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/abed-the-astronaut-community-joseph-oland.jpg",
                            Private = false,
                            ProfileId = 1,
                            StyleId = 1,
                            Title = "Up"
                        },
                        new
                        {
                            Id = 3,
                            PostImg = "https://obiruskenobi.files.wordpress.com/2013/11/greendale_final.jpg",
                            Private = false,
                            ProfileId = 2,
                            StyleId = 2,
                            Title = "The Greendale Dead"
                        },
                        new
                        {
                            Id = 4,
                            PostImg = "https://images.theconversation.com/files/296052/original/file-20191008-128681-ngzwqb.jpg?ixlib=rb-1.1.0&rect=15%2C20%2C929%2C926&q=20&auto=format&w=320&fit=clip&dpr=2&usm=12&cs=strip",
                            Private = true,
                            ProfileId = 2,
                            StyleId = 2,
                            Title = "Arts!"
                        });
                });

            modelBuilder.Entity("CommissionMe.Models.PostTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("TagId");

                    b.HasIndex("PostId", "TagId")
                        .IsUnique();

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("CommissionMe.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("text");

                    b.Property<string>("Rates")
                        .HasColumnType("text");

                    b.Property<int[]>("StyleIds")
                        .HasColumnType("integer[]");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Troy... Troy Barnes?... Barnes comma Troy??",
                            Email = "tbone@greendale.edu",
                            Experience = "3-5 Years",
                            Name = "Troy Barnes",
                            ProfilePic = "https://i.redd.it/3fbg5y6884351.jpg",
                            Rates = "$200-300",
                            StyleIds = new[] { 1, 3, 19 },
                            Uid = "V9gg3039YHROMJ6pH8tPD84Qrzh2"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "It's called 'Showbusiness,' not 'Friendbusiness...'",
                            Email = "CoolAbedProductions@greendale.edu",
                            Experience = "6-9 Years",
                            Name = "Abed Nadir",
                            ProfilePic = "https://spacecrip.files.wordpress.com/2012/04/abed.png?w=640",
                            Rates = "300+",
                            StyleIds = new[] { 2, 3, 4, 6, 8, 15, 17 },
                            Uid = "WDnlUTXgAxfAgRjrNebr6dppvC83"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "That's nice!",
                            Email = "ShirleysSandwiches@greendale.edu",
                            Experience = "3-5 Years",
                            Name = "Shirley Bennett",
                            ProfilePic = "https://assets.mycast.io/characters/shirley-bennett-6527587-normal.jpg?1659645717",
                            Rates = "$200-300",
                            StyleIds = new[] { 3, 5, 12, 14 },
                            Uid = "KC1UeRhu8ATnVAodM8uMDIi9Brh2"
                        });
                });

            modelBuilder.Entity("CommissionMe.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("StyleName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StyleName = "Landscapes"
                        },
                        new
                        {
                            Id = 2,
                            StyleName = "Pop"
                        },
                        new
                        {
                            Id = 3,
                            StyleName = "Commercial"
                        },
                        new
                        {
                            Id = 4,
                            StyleName = "Abstract"
                        },
                        new
                        {
                            Id = 5,
                            StyleName = "Realism"
                        },
                        new
                        {
                            Id = 6,
                            StyleName = "Impressionism"
                        },
                        new
                        {
                            Id = 7,
                            StyleName = "Photorealism"
                        },
                        new
                        {
                            Id = 8,
                            StyleName = "Portrait"
                        },
                        new
                        {
                            Id = 9,
                            StyleName = "Expressionism"
                        },
                        new
                        {
                            Id = 10,
                            StyleName = "Minimalism"
                        },
                        new
                        {
                            Id = 11,
                            StyleName = "Surrealism"
                        },
                        new
                        {
                            Id = 12,
                            StyleName = "Digital"
                        },
                        new
                        {
                            Id = 13,
                            StyleName = "Graffiti"
                        },
                        new
                        {
                            Id = 14,
                            StyleName = "Conceptual"
                        },
                        new
                        {
                            Id = 15,
                            StyleName = "Anime/Toon"
                        });
                });

            modelBuilder.Entity("CommissionMe.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TagName = "Bright"
                        },
                        new
                        {
                            Id = 2,
                            TagName = "Photography"
                        },
                        new
                        {
                            Id = 3,
                            TagName = "Logo"
                        },
                        new
                        {
                            Id = 4,
                            TagName = "Dark"
                        },
                        new
                        {
                            Id = 5,
                            TagName = "Portrait"
                        },
                        new
                        {
                            Id = 6,
                            TagName = "Abstract"
                        },
                        new
                        {
                            Id = 7,
                            TagName = "Surreal"
                        },
                        new
                        {
                            Id = 8,
                            TagName = "Beauty"
                        },
                        new
                        {
                            Id = 9,
                            TagName = "Scary"
                        },
                        new
                        {
                            Id = 10,
                            TagName = "Peaceful"
                        },
                        new
                        {
                            Id = 11,
                            TagName = "Realistic"
                        },
                        new
                        {
                            Id = 12,
                            TagName = "Cartoon"
                        },
                        new
                        {
                            Id = 13,
                            TagName = "Anime"
                        },
                        new
                        {
                            Id = 14,
                            TagName = "Bold"
                        },
                        new
                        {
                            Id = 15,
                            TagName = "Minimal"
                        },
                        new
                        {
                            Id = 16,
                            TagName = "Folksy"
                        },
                        new
                        {
                            Id = 17,
                            TagName = "Modern"
                        },
                        new
                        {
                            Id = 18,
                            TagName = "Classic"
                        },
                        new
                        {
                            Id = 19,
                            TagName = "Retro"
                        },
                        new
                        {
                            Id = 20,
                            TagName = "Urban"
                        },
                        new
                        {
                            Id = 21,
                            TagName = "Futuristic"
                        },
                        new
                        {
                            Id = 22,
                            TagName = "Sci-Fi"
                        },
                        new
                        {
                            Id = 23,
                            TagName = "Fantasy"
                        });
                });

            modelBuilder.Entity("CommissionMe.Models.Post", b =>
                {
                    b.HasOne("CommissionMe.Models.Profile", null)
                        .WithMany("Posts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommissionMe.Models.PostTag", b =>
                {
                    b.HasOne("CommissionMe.Models.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommissionMe.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CommissionMe.Models.Style", b =>
                {
                    b.HasOne("CommissionMe.Models.Profile", null)
                        .WithMany("Styles")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("CommissionMe.Models.Post", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("CommissionMe.Models.Profile", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Styles");
                });

            modelBuilder.Entity("CommissionMe.Models.Tag", b =>
                {
                    b.Navigation("PostTags");
                });
#pragma warning restore 612, 618
        }
    }
}
